modLoader="javafml"
loaderVersion="[41,)"
license="GNU Lesser General Public License version 3"

[[mods]] 
modId="varietree"
version="1.19.2-1.1.1"
displayName="Varietree"
logoFile="thumbnail.png"
credits="By PaulerLeOne" 
authors="PaulerLeOne"
description='''
This mod aims to add new varieties to the already existing types of tree. 
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[41,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="SERVER"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
